=begin
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
=end

n = 0

pent_ary = Array.new
hex_ary = Array.new

while true do
n = n + 1
tri = n*(n+1)/2
pent = (n*((3*n)-1))/2
hex = n*((2*n)-1)
pent_ary.push(pent)
hex_ary.push(hex)
	if n > 285 && pent_ary.include?(tri) && hex_ary.include?(tri)
		puts tri
		exit
	end
end